test1 = error(show(1))
